---
# vars file for roles/setup-network

# repository
network_launch_repository: github.com/dojimanetwork/launch
# branch
network_launch_branch: master
# version
network_version: dojima-t1
# node type
# options: sentry/sentry, sentry/validator, without-sentry
node_type: without-sentry
